refactor(hexonet/responsetranslator.php): auto-reword DNS update error
centralnicgroup-opensource/rtldev-middleware-php-sdk pull request #44
Opened 2023-08-09 14:57 UTC by AsifNawaz-cnic

Skip key 'SkipPregQuote' for preg_quote and allow array keys to have a regex

2023-08-21 10:59 UTC, KaiSchwarz-cnic requested changes
change the commit type to "fix" please so that a new version is getting released.

ty!

2023-08-21 11:21 UTC, AsifNawaz-cnic commented
Changed the commit type to "fix", please review :) ty

2023-08-22 07:42 UTC, KaiSchwarz-cnic approved these changes

2023-08-22 07:42 UTC, merged

2023-08-24 09:17 UTC, KaiSchwarz-cnic commented
:tada: This PR is included in version 8.0.11 :tada:

The release is available on [GitHub release](https://github.com/centralnicgroup-opensource/rtldev-middleware-php-sdk/releases/tag/v8.0.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: